homeassistant:
  customize:
    alarm_control_panel.alarma:
      friendly_name: Alarma del hogar
      icon: mdi:shield-home
    input_boolean.mirror_eve_main_door:
      friendly_name: Puerta principal
      icon: mdi:door-closed
    input_boolean.alarm_auto_arm_when_exit_home:
      friendly_name: Auto-arm at exit
      icon: mdi:shield-key-outline
    input_boolean.alarm_notify_events:
      friendly_name: Alarm event notifications
      icon: mdi:shield-alert-outline

###############################################################################
# ALARM PANEL
###############################################################################
input_boolean:
  mirror_eve_main_door:
    initial: off

  alarm_auto_arm_when_exit_home:
    initial: on
  alarm_notify_events:
    initial: on

binary_sensor:
  - platform: template
    sensors:
      mirror_eve_main_door:
        friendly_name: Puerta principal
        device_class: door
        value_template: >-
          {{ is_state('input_boolean.mirror_eve_main_door', 'on') }}
        entity_id:
        - input_boolean.mirror_eve_main_door

alarm_control_panel:
  - platform: manual
    name: Alarma

    # default is armed_away
    # ∆ before changing to triggered
    delay_time: 0
    # ∆ before changing to anything else (not triggered)
    pending_time: 20
    # Trigger duration
    trigger_time: 60

    triggered:
      pending_time: 1
    disarmed:
      delay_time: 0
      trigger_time: 0
    armed_home:
      pending_time: 10
      delay_time: 10
      trigger_time: 180
    armed_night:
      pending_time: 0
      delay_time: 20
      trigger_time: 30
