homeassistant:
  customize:
    alarm_control_panel.alarma:
      friendly_name: Alarma del hogar
      icon: mdi:shield-home
    input_boolean.mirror_eve_main_door:
      friendly_name: Puerta principal
      icon: mdi:door-closed
    input_boolean.alarm_auto_arm_when_exit_home:
      friendly_name: Auto-arm at exit
      icon: mdi:shield-key-outline
    input_boolean.alarm_notify_events:
      friendly_name: Alarm event notifications
      icon: mdi:shield-alert-outline

###############################################################################
# ALARM PANEL
###############################################################################
input_boolean:
  alarm_auto_arm_when_exit_home:
    initial: on
  alarm_notify_events:
    initial: on

alarm_control_panel:
  - platform: manual
    name: Alarma

    # default is armed_away
    # ∆ before changing to triggered
    delay_time: 5
    # ∆ before changing to anything else (not triggered)
    arming_time: 45
    # Trigger duration
    trigger_time: 60

    #triggered:
    #  pending_time: 1
    #disarmed:
    #  delay_time: 0
    #  trigger_time: 0
    armed_home:
      arming_time: 10
      delay_time: 20
      trigger_time: 60
    armed_night:
      arming_time: 60
      delay_time: 20
      trigger_time: 20
