homeassistant:
  customize:
    camera.pi_zero_cam_1:
      friendly_name: Salón
    camera.pi_zero_cam_2:
      friendly_name: Cocina
    camera.escam:
      friendly_name: Office

    switch.motion_detection_escam:
      friendly_name: VideoMov. Office
      icon: mdi:video
    switch.motion_detection_pizerocam1:
      friendly_name: VideoMov. Salón
      icon: mdi:video
    switch.motion_detection_pizerocam2:
      friendly_name: VideoMov. Cocina
      icon: mdi:video

switch:
- platform: template
  scan_interval: 60
  switches:
    motion_detection_pizerocam1:
      value_template: "{{ is_state('camera.pi_zero_cam_1', 'recording') }}"
      entity_id: camera.pi_zero_cam_1
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_1
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_1
    motion_detection_pizerocam2:
      value_template: "{{ is_state('camera.pi_zero_cam_2', 'recording') }}"
      entity_id: camera.pi_zero_cam_2
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_2
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_2
    motion_detection_escam:
      value_template: "{{ is_state('camera.escam', 'recording') }}"
      entity_id: camera.escam
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.escam
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.escam

###############################################################################
# IP CAMERAS (from Motioneye
###############################################################################
camera:
  # Kitchen camera
  - platform: motioneye
    snapshot_url: !secret motioneye_rpizero2_snapshot_url
    name: Pi Zero Cam 2
    with_motion_control: true
    control_port: 7999
    camera_id: 1

  # Living room camera
  - platform: motioneye
    snapshot_url: !secret motioneye_rpizero_snapshot_url
    name: Pi Zero Cam 1
    with_motion_control: true
    control_port: 7999
    camera_id: 1

#  # Office camera
  - platform: motioneye
    snapshot_url: !secret escam_motioneye_local_snapshot
    name: Escam
    with_motion_control: true
    control_port: 7999
    camera_id: 1

###############################################################################
# PTZ ESCAM
###############################################################################
shell_command:
  # PTZ camera commands
  cmd_set_escam_door: '/config/shell/escam_ptz.py door'
  cmd_set_escam_window: '/config/shell/escam_ptz.py window'
