homeassistant:
  customize:
    sensor.ip_externa:
      friendly_name: IP externa
      icon: mdi:map-marker
    binary_sensor.internet_online:
      friendly_name: "¿Hay conexión a internet?"

binary_sensor:
- platform: ping
  name: Internet Online
  host: 8.8.8.8
  count: 1
  device_class: connectivity
  scan_interval: 90

- platform: template
  sensors:
    services_notok:
      friendly_name: Problemas
      device_class: safety
      value_template: "{{ (states.sensor.nut_ups_status.state != 'Online') or (states.binary_sensor.internet_online.state != 'on') or (states.sensor.ip_externa.state == 'unknown') }}"
      entity_id:
        - sensor.nut_ups_status
        - sensor.ip_externa
        - binary_sensor.internet_online

sensor:
- platform: rest
  resource: http://ip.jsontest.com
  name: IP Externa
  value_template: '{% if value_json %}{{ value_json.ip }}{% else %}{{ states.sensor.ip_externa.state}}{% endif %}'
  scan_interval: 150

#- platform: cert_expiry
#  host: !secret base_host
#  scan_interval: 7200

- platform: uptime
  unit_of_measurement: hours
