homeassistant:
  customize:
    sensor.temperatura_interior:
      icon: mdi:thermometer
      hidden: true
    sensor.temperatura_stats_mean:
      friendly_name: Temperatura interior (rm)
      icon: mdi:thermometer
    sensor.temperatura_ac:
      icon: mdi:thermometer
      hidden: true
    sensor.temperatura_ac_mean:
      friendly_name: Temperatura AC (rm)
      icon: mdi:thermometer

    sensor.temperatura_exterior:
      icon: mdi:thermometer

    sensor.temp_acs_max:
      friendly_name: ACS Máx Ret Solar
      icon: mdi:temperature-celsius

    sensor.humedad_interior:
      icon: mdi:water-percent
      hidden: true
      device_class: humidity
    sensor.humedad_stats_mean:
      friendly_name: Humedad interior (rm)
      icon: mdi:water-percent
      device_class: humidity
    sensor.humedad_exterior:
      icon: mdi:water-percent
      device_class: humidity

    input_boolean.ac_target_include_livingroom:
      friendly_name: AC Salón
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_study:
      friendly_name: AC Estudio
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_office:
      friendly_name: AC Office
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_bedroom:
      friendly_name: AC Dormitorio
      icon: mdi:toggle-switch

sensor:
  - platform: min_max
    type: mean
    name: Temperatura Office
    round_digits: 1
    entity_ids:
      -  sensor.airpurifier_office_temperature
      -  sensor.sensor_office_temperature

  - platform: min_max
    type: mean
    name: Temperatura AC
    round_digits: 1
    entity_ids:
      -  sensor.sensor_livingroom_temperature
      -  sensor.sensor_study_temperature
      -  sensor.sensor_office_temperature
      -  sensor.dormitorio_temperature_rpi2mpd

#  - platform: statistics
#    entity_id: sensor.temperatura_ac
#    name: temperatura_ac_mean
#    sampling_size: 100
#    precision: 1
#    max_age:
#      minutes: 10

  - platform: min_max
    type: mean
    name: Temperatura interior
    round_digits: 1
    entity_ids:
      -  sensor.sensor_kitchen_temperature
      -  sensor.sensor_study_temperature
      -  sensor.sensor_office_temperature
      -  sensor.sensor_livingroom_temperature
      -  sensor.multi_2_temperature
      -  sensor.dormitorio_temperature_rpi2mpd
      -  sensor.sensor_bathroom_ac_temperature

  - platform: min_max
    type: min
    name: Temperatura exterior
    round_digits: 1
    entity_ids:
      -  sensor.sensor_terraza_temperature
      -  sensor.sensor_galeria_temperature

  - platform: min_max
    type: min
    name: Temperatura exterior zigbee
    round_digits: 1
    entity_ids:
      - sensor.multi_1_temperature
      - sensor.multi_3_temperature

  - platform: min_max
    type: mean
    round_digits: 1
    name: Humedad interior
    entity_ids:
      -  sensor.sensor_kitchen_humidity
      -  sensor.sensor_study_humidity
      -  sensor.sensor_office_humidity
      -  sensor.sensor_livingroom_humidity
      -  sensor.dormitorio_humidity_rpi2mpd
      -  sensor.sensor_bathroom_ac_humidity
      -  sensor.multi_2_humidity

  - platform: min_max
    type: mean
    name: Humedad exterior
    round_digits: 1
    entity_ids:
      -  sensor.sensor_terraza_humidity
      -  sensor.sensor_galeria_humidity
      -  sensor.multi_1_humidity
      -  sensor.multi_3_humidity

#  - platform: statistics
#    entity_id: sensor.temperatura_interior
#    name: temperatura_stats_mean
#    precision: 1
#    sampling_size: 50
#    max_age:
#      minutes: 15

#  - platform: statistics
#    entity_id: sensor.temperatura_exterior
#    name: temperatura_ext_stats_mean
#    precision: 1
#    sampling_size: 50
#    max_age:
#      minutes: 15

#  - platform: statistics
#    name: humedad_stats_mean
#    precision: 1
#    sampling_size: 50
#    entity_id: sensor.humedad_interior
#    max_age:
#      minutes: 15

#  - platform: statistics
#    name: UPS mean Power
#    precision: 0
#    sampling_size: 6  # := 3 min
#    entity_id: sensor.nut_ups_power
#    max_age:
#      minutes: 3

binary_sensor:
  - platform: template
    sensors:
      show_ac_heat:
        friendly_name: "Calefacción posible"
        unique_id: "manual_template_calefaccion_posible"
        device_class: 'heat'
        entity_id:
          - sensor.temperatura_ac_mean
          - sensor.temperatura_ext_stats_mean
          - sensor.season
        delay_on: "1:00:00"
        delay_off: "2:00:00"
        value_template: >-
          {{ (states.sensor.season != "summer") and (states.sensor.temperatura_ac_mean.state | float < 23) and (states.sensor.temperatura_ext_stats_mean.state | float < 21) }}
        attribute_templates:
          t_ext: '{{ states.sensor.temperatura_exterior.state }}'
          t_int: '{{ states.sensor.temperatura_ac_mean.state }}'
          season: '{{ states.sensor.season.state }}'
      show_ac_cool:
        friendly_name: "AC posible"
        unique_id: "manual_template_aire_acondicionado_posible"
        device_class: 'cold'
        delay_on: "0:30:00"
        delay_off: "2:00:00"
        entity_id:
          - sensor.temperatura_ac_mean
          - sensor.temperatura_ext_stats_mean
          - binary_sensor.show_ac_heat
          - sensor.season
        value_template: >-
          {{ (states.sensor.season == "summer") or ((states.sensor.season != "winter") and (states.binary_sensor.show_ac_heat.state == "off") and (states.sensor.temperatura_ac_mean.state | float > 21) and (states.sensor.temperatura_ext_stats_mean.state | float > 20)) }}
        attribute_templates:
          t_ext: '{{ states.sensor.temperatura_exterior.state }}'
          t_int: '{{ states.sensor.temperatura_ac_mean.state }}'
          season: '{{ states.sensor.season.state }}'

      ups_active:
        friendly_name: "Computer ON"
        unique_id: "manual_template_computer_on"
        delay_off: "0:01:00"
        entity_id:
          - sensor.ups_mean_power
        device_class: 'occupancy'
        value_template: >-
          {{ (states.sensor.ups_mean_power.state | int) > 75 }}
        attribute_templates:
          ups_power: '{{ states.sensor.ups_mean_power.state }}'
          ups_power_instant: '{{ states.sensor.nut_ups_power.state }}'
