homekit:
  name: Casa
  filter:
    include_domains:
      - alarm_control_panel
      - cover
      - climate
      - vacuum
    include_entities:
      - media_player.kodi_tv
      - light.yeelight_strip_7811dca21ecf

      - light.hall_light

      - switch.calentador
#      - switch.03200296dc4f22293a7f
#      - switch.15556050840d8ea15efb_1
#      - switch.15556050840d8ea15efb_2
#      - switch.tplink1

      - input_boolean.mirror_eve_main_door

      - sensor.sensor_galeria_humidity
      - sensor.sensor_galeria_temperature
      - sensor.sensor_kitchen_humidity
      - sensor.sensor_kitchen_temperature
      - sensor.sensor_livingroom_humidity
      - sensor.sensor_livingroom_temperature
      - sensor.sensor_office_humidity
      - sensor.sensor_office_temperature
      - sensor.sensor_study_humidity
      - sensor.sensor_study_temperature
      - sensor.sensor_terraza_humidity
      - sensor.sensor_terraza_temperature
      - sensor.dormitorio_humidity_rpi2mpd
      - sensor.dormitorio_temperature_rpi2mpd

      - script.play_kodi_pvr
      - script.start_tvshows_mode
      - script.quick_cool_session
      - script.quick_heat_session
      - script.start_vacuum
#      - scene.golpe_de_frio
#      - scene.la_caja_tonta
#      - scene.modo_series
  entity_config:
    media_player.kodi_tv:
      name: Tele
      feature_list:
        - feature: on_off
#        - feature: play_pause
#        - feature: play_stop
#    switch.03200296dc4f22293a7f:
#      type: valve
#      name: Bomba ACS
#    # Smart wifi plug 2 in 1
#    switch.15556050840d8ea15efb_1:
#      type: outlet
#      name: Ladrón baño 1
#    switch.15556050840d8ea15efb_2:
#      type: outlet
#      name: Ladrón baño 2
    switch.calentador:
      type: shower
      name: Calentador

    script.play_kodi_pvr:
      name: La caja tonta
    script.start_tvshows_mode:
      name: Modo series
    script.quick_cool_session:
      name: Golpe de frío
