# HUE LIGHTS
homeassistant:
  customize:
    light.bola_grande:
      icon: mdi:ceiling-light
    light.terraza:
      icon: mdi:lightbulb-outline
    light.hue_habitacion:
      icon: mdi:ceiling-light
    light.aura_habitacion:
      icon: mdi:lava-lamp
    light.pie_tv:
      icon: mdi:lamp
    light.pie_sofa:
      icon: mdi:lamp
    light.cuenco:
      icon: mdi:lava-lamp
    light.lamparita:
      icon: mdi:lava-lamp
    light.flexo:
      icon: mdi:lightbulb-outline
    light.central:
      icon: mdi:ceiling-light
    light.go:
      icon: mdi:lava-lamp
    light.tira:
      icon: mdi:dots-horizontal
    light.tira_cocina:
      icon: mdi:dots-horizontal
    light.ambilight:
      icon: mdi:monitor-star
    switch.ambilight_plus_hue:
      friendly_name: Hue + Ambilight
      icon: mdi:traffic-light

    sensor.interruptor_office:
      icon: mdi:light-switch
    sensor.interruptor_cocina:
      icon: mdi:light-switch
    sensor.interruptor_exterior:
      icon: mdi:remote

    remote.interruptor_salon:
      icon: mdi:light-switch
    remote.interruptor_dormitorio:
      icon: mdi:light-switch
    remote.interruptor_estudio:
      icon: mdi:light-switch

hue:
  bridges:
    - host: !secret hue_bridge_host
      allow_unreachable: true

# sensors from events for hue switches in deconz
sensor:
  - platform: eventsensor
    name: Interruptor exterior
    event: deconz_event
    state: event
    state_map:
      34: 1_click
      16: 2_click
      17: 3_click
      18: 4_click
    event_data:
      unique_id: 00:00:00:00:00:45:51:23

  - platform: eventsensor
    name: Interruptor office
    event: deconz_event
    event_data:
      id: interruptor_office
    state: event
    state_map:
      1000: 1_click
      2000: 2_click
      3000: 3_click
      4000: 4_click
      1001: 1_hold
      2001: 2_hold
      3001: 3_hold
      4001: 4_hold
      1002: 1_click_up
      2002: 2_click_up
      3002: 3_click_up
      4002: 4_click_up
      1003: 1_hold_up
      2003: 2_hold_up
      3003: 3_hold_up
      4003: 4_hold_up

  - platform: eventsensor
    name: Interruptor cocina
    event: deconz_event
    event_data:
      id: interruptor_cocina
    state: event
    state_map:
      1000: 1_click
      2000: 2_click
      3000: 3_click
      4000: 4_click
      1001: 1_hold
      2001: 2_hold
      3001: 3_hold
      4001: 4_hold
      1002: 1_click_up
      2002: 2_click_up
      3002: 3_click_up
      4002: 4_click_up
      1003: 1_hold_up
      2003: 2_hold_up
      3003: 3_hold_up
      4003: 4_hold_up

# hue switches
remote:
- platform: hueremote

# Philips TV Ambilight support with custom component
light:
- platform: ambilights
  name: Ambilight
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password

switch:
- platform: ambilights
  name: ambilight_plus_hue
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password
  scan_interval: 15

input_select:
  salon_light_scene:
    name: Escena de luz
    options:
     - Concentración
     - Energía
     - Relax
     - Lectura
     - Estudio
#     - Comida
#     - Cena
     - Atardecer
     - Aurora boreal
     - Flor primaveral
     - Ocaso tropical
     - TV Night
     - 'OFF'
    initial: Energía
    icon: mdi:lightbulb

input_boolean:
  app_lights_automation: