# HUE LIGHTS
homeassistant:
  customize:
    light.bola:
      icon: mdi:ceiling-light
    light.terraza:
      icon: mdi:lightbulb-outline
    light.hue_habitacion:
      icon: mdi:ceiling-light
    light.aura_habitacion:
      icon: mdi:lava-lamp
    light.pie_tv:
      icon: mdi:lamp
    light.pie_sofa:
      icon: mdi:lamp
    light.cuenco:
      icon: mdi:lava-lamp
    light.lamparita:
      icon: mdi:lava-lamp
    light.flexo:
      icon: mdi:lightbulb-outline
    light.central:
      icon: mdi:ceiling-light
    light.go:
      icon: mdi:lava-lamp
    light.tira:
      icon: mdi:dots-horizontal
    light.tira_tv:
      icon: mdi:dots-horizontal
    light.tira_cocina:
      icon: mdi:dots-horizontal
    light.ambilight:
      icon: mdi:monitor-star
    switch.ambilight_plus_hue:
      friendly_name: Hue + Ambilight
      icon: mdi:traffic-light

    sensor.interruptor_office:
      icon: mdi:light-switch
    sensor.interruptor_cocina:
      icon: mdi:light-switch
    sensor.interruptor_exterior:
      icon: mdi:google-circles-communities

    sensor.interruptor_salon:
      icon: mdi:light-switch
    sensor.interruptor_dormitorio:
      icon: mdi:light-switch
    sensor.interruptor_estudio:
      icon: mdi:light-switch

#hue:
#  bridges:
#    - host: !secret hue_bridge_host
#      allow_unreachable: true

# sensors from events for hue switches in deconz & hue --> in UI -> eventsensor CC

# Philips TV Ambilight support with custom component
light:
- platform: ambilights
  name: Ambilight
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password

switch:
- platform: ambilights
  name: ambilight_plus_hue
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password
  scan_interval: 15

input_select:
  salon_light_scene:
    name: Escena de luz
    options:
     - Concentración
     - Energía
     - Relax
     - Lectura
     - Estudio
#     - Comida
#     - Cena
     - Atardecer
     - Aurora boreal
     - Flor primaveral
     - Ocaso tropical
     - TV Night
     - 'OFF'
    initial: Energía
    icon: mdi:lightbulb

input_boolean:
  app_lights_automation: