# HUE LIGHTS
homeassistant:
  customize:
    light.bola_grande:
      icon: mdi:ceiling-light
    light.terraza:
      icon: mdi:lightbulb-outline
    light.hue_habitacion:
      icon: mdi:ceiling-light
    light.aura_habitacion:
      icon: mdi:lava-lamp
    light.pie_tv:
      icon: mdi:lamp
    light.pie_sofa:
      icon: mdi:lamp
    light.cuenco:
      icon: mdi:lava-lamp
    light.lamparita:
      icon: mdi:lava-lamp
    light.flexo:
      icon: mdi:lightbulb-outline
    light.central:
      icon: mdi:ceiling-light
    light.go:
      icon: mdi:lava-lamp
    light.tira:
      icon: mdi:dots-horizontal
    light.tira_cocina:
      icon: mdi:dots-horizontal
    light.ambilight:
      icon: mdi:monitor-star
    switch.ambilight_plus_hue:
      friendly_name: Hue + Ambilight
      icon: mdi:traffic-light

    remote.interruptor_salon:
      icon: mdi:light-switch
    remote.interruptor_dormitorio:
      icon: mdi:light-switch
    remote.interruptor_estudio:
      icon: mdi:light-switch
    remote.interruptor_cocina:
      icon: mdi:light-switch
    remote.interruptor_office:
      icon: mdi:light-switch

    input_boolean.mirror_hue_motion_1:
      friendly_name: Movimiento cocina (Hue)
      icon: mdi:run
    input_boolean.mirror_hue_motion_2:
      friendly_name: Movimiento office (Hue)
      icon: mdi:run

hue:
  bridges:
    - host: !secret hue_bridge_host
      allow_unreachable: true

# hue dimmer switches
remote:
- platform: huesensor
#  scan_interval: 1

# Philips TV Ambilight support with custom component
light:
- platform: ambilights
  name: Ambilight
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password

switch:
- platform: ambilights
  name: ambilight_plus_hue
  host: !secret philips_tv_host
  username: !secret philips_tv_api_username
  password: !secret philips_tv_api_password
  scan_interval: 15

input_select:
  salon_light_scene:
    name: Escena de luz
    options:
     - Concentración
     - Energía
     - Relax
     - Lectura
     - Estudio
#     - Comida
#     - Cena
     - Atardecer
     - Aurora boreal
     - Flor primaveral
     - Ocaso tropical
     - TV Night
     - 'OFF'
    initial: Energía
    icon: mdi:lightbulb

# for binary_sensor.hue_motion_sensor_1_motion and binary_sensor.hue_motion_sensor_2_motion
input_boolean:
  mirror_hue_motion_1:
    initial: off
  mirror_hue_motion_2:
    initial: off
