####################################################
#                     Notify                       #
####################################################
notify:
  - platform: smtp
    name: gmail
    server: smtp.gmail.com
    port: 587
    sender: !secret hass_email
    sender_name: !secret name
    encryption: starttls
    username: !secret hass_email
    password: !secret hass_email_pw
    recipient: !secret myemail
    timeout: 60

  - platform: telegram
    name: telegram_bot
    chat_id: !secret telegram_bot_chat_id_admin

  - platform: telegram
    name: telegram_group
    chat_id: !secret telegram_bot_group

  - platform: group
    name: ios_devices
    services:
      - service: !secret ios_notifier_main
      - service: !secret ios_notifier_main_ipad
      - service: !secret ios_notifier_secondary
      - service: !secret ios_notifier_secondary_ipad

#####################################################
##                     Telegram BOT                 #
#####################################################
telegram_bot:
  platform: polling
#  platform: webhooks
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_admin
    - !secret telegram_bot_chat_id_2
    - !secret telegram_bot_group

#####################################################
##                     iOS platform                 #
#####################################################
ios:
  push:
    categories:
      - name: away
        identifier: 'away'
        actions:
          - identifier: 'ALARM_ARM_NOW'
            title: 'Activar alarma'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            context: 'default'
          - identifier: 'ALARM_HOME'
            title: 'Activar vigilancia'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            context: 'default'
          - identifier: 'LIGHTS_OFF'
            title: 'Apagar luces'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'

      - name: inhome
        identifier: 'inhome'
        actions:
          - identifier: 'WELCOME_HOME'
            title: 'Encender luces'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'WELCOME_HOME_TV'
            title: 'Encender la TV'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'IGNORE_HOME'
            title: 'Ignorar la llegada'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
            context: 'default'

      - name: alarmsounded
        identifier: 'alarmsounded'
        actions:
          - identifier: 'ALARM_SILENT'
            title: 'Silenciar'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'ALARM_RESET'
            title: 'Ignorar (reset)'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            context: 'default'
          - identifier: 'ALARM_CANCEL'
            title: 'Desconectar'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
            context: 'default'

      - name: confirm
        identifier: 'confirm'
        actions:
          - identifier: 'CONFIRM_OK'
            title: 'Validar'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'minimal'

      - name: kodiplay
        identifier: 'kodiplay'
        actions:
          - identifier: 'LIGHTS_ON'
            title: 'Lights ON!'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'TV_NIGHT_MODE'
            title: 'Night mode'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'COVERS_DOWN'
            title: 'Cierra persianas'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
            context: 'default'
          - identifier: 'HUE_AMBI_TOGGLE'
            title: 'Toggle Ambilight+Hue'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'

      - name: alarmclock
        identifier: 'alarmclock'
        actions:
          - identifier: 'INIT_DAY'
            title: 'A la ducha!'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'POSTPONE_ALARMCLOCK'
            title: 'Postponer...'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'ALARMCLOCK_OFF'
            title: 'Apagar'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
            context: 'default'

      - name: powerpeak
        identifier: 'powerpeak'
        actions:
          - identifier: 'TURN_OFF_ACS'
            title: 'Apaga Calentador'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'TURN_OFF_CLIMATE'
            title: 'Apaga AC'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'TURN_OFF_ALL'
            title: 'Apaga todo!'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            context: 'default'

      - name: airpurif
        identifier: 'airpurif'
        actions:
          - identifier: 'PURIFIER_SILENT'
            title: 'Al mínimo'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'PURIFIER_SET_LEVEL'
            title: 'Velocidad fija'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'PURIFIER_OFF'
            title: 'Apagar'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
            context: 'default'

      - name: camera
        identifier: 'camera'
        actions:
          - identifier: 'ALARM_CANCEL'
            title: 'Desconectar'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
            context: 'default'
          - identifier: 'ALARM_RESET'
            title: 'Ignorar (reset)'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            context: 'default'
          - identifier: 'CONFIRM_OK'
            title: 'Validar'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
            context: 'minimal'

      - name: inputtext
        identifier: 'inputtext'
        actions:
          - identifier: 'INPUTORDER'
            title: 'Tell me'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'textInput'
            context: 'default'
            textInputButtonTitle: "What?" # Only for iOS 10 when behavior is TextInput.
            textInputPlaceholder: 'tell me more' # Only for iOS 10 when behavior is TextInput.
