homeassistant:
  customize:
    binary_sensor.pasillo_mov:
      friendly_name: 'Movimiento (pasillo)'
    binary_sensor.hall_mov:
      friendly_name: 'Movimiento (hall)'
    binary_sensor.alarm_moisture:
      friendly_name: 'Sensor de inundación'
    binary_sensor.alarm_smoke:
      friendly_name: 'Sensor de humo'

# Discovery for shelly devs with hacs custom component
shelly:
  discovery: false
  settings:
    temperature: { decimals: 1 }
  username: !secret shelly_user
  password: !secret shelly_pwd
  devices:  #configure devices
    - id: !secret shelly_id_cover_ventanal
      name: Persiana Ventanal
    - id: !secret shelly_id_cover_puerta
      name: Persiana Puerta terraza
    - id: !secret shelly_id_em
      name: Current Meter
    - id: !secret shelly_id_cuadro_mov
      name: Sensores movimiento
    - id: !secret shelly_id_cuadro_alerts
      name: Alarmas técnicas
    - id: !secret shelly_id_hall
      name: Luz Hall
      light_switch: true
    - id: !secret shelly_id_pasillo
      name: Luz Pasillo
      light_switch: true

# MQTT connection (for quick response) for some devices
binary_sensor:
  - platform: mqtt
    device_class: motion
    unique_id: "manual-mqtt-binsensor-hall_mov"
    name: hall_mov
    state_topic: "shellies/shelly25-mov/input/0"
    payload_on: "1"
    payload_off: "0"
    qos: 1

  - platform: mqtt
    device_class: motion
    unique_id: "manual-mqtt-binsensor-pasillo_mov"
    name: pasillo_mov
    state_topic: "shellies/shelly25-mov/input/1"
    payload_on: "1"
    payload_off: "0"
    qos: 1

  - platform: mqtt
    device_class: moisture
    unique_id: "manual-mqtt-binsensor-alarm_moisture"
    name: alarm_moisture
    state_topic: "shellies/shelly25-cuadro/input/0"
    payload_on: "1"
    payload_off: "0"
    qos: 1

  - platform: mqtt
    device_class: smoke
    unique_id: "manual-mqtt-binsensor-alarm_smoke"
    name: alarm_smoke
    state_topic: "shellies/shelly25-cuadro/input/1"
    payload_on: "1"
    payload_off: "0"
    qos: 1
