homeassistant:
  customize:
    input_select.esp_command:
      icon: mdi:developer-board
    input_select.esp_modules:
      icon: mdi:developer-board
    sensor.processor_use:
      icon: mdi:chip

  # Customize entities matching a pattern
  customize_glob:
    "sensor.speedtest*":
      icon: mdi:speedometer

sentry:
  dsn: !secret sentry_dsn

timer:
  alarm_auto_on:
    duration: '00:05:00'
    icon: mdi:alarm-check

variable:
  speedtest_data:
    value: 0
    attributes:
      icon: mdi:speedometer

input_select:
  esp_command:
    name: Comandos
    options:
     - Restart
     - Wifi_scan
  esp_modules:
    name: Módulos
    options:
     - Terraza
     - Salón
     - Dormitorio
     - Baño
     - Office
     - Cocina
     - Galería

sensor:
- platform: time_date
  display_options:
  - 'time_utc'
  - 'date_time'

- platform: command_line
  name: HASS CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
  scan_interval: 30

- platform: template
  sensors:
    speedtest_ping:
      friendly_name: "Speedtest Ping"
      unit_of_measurement: 'ms'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.ping.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_upload:
      friendly_name: "Speedtest Upload"
      unit_of_measurement: 'Mbit/s'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.upload.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_download:
      unit_of_measurement: 'Mbit/s'
      friendly_name: "Speedtest Download"
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.download.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data

#- platform: speedtest
#  minute:
#    - 35
#  monitored_conditions:
#    - ping
#    - download
#    - upload


shell_command:
  # Init SSH keys
  cmd_init_ssh_identity: '/config/shell/start_ssh_keys.sh'
