homeassistant:
  customize:
    sensor.yw_day1_condition:
      friendly_name: Mañana
    sensor.yw_day1_temperature_min:
      friendly_name: Mínima mañana
    sensor.yw_day1_temperature_max:
      friendly_name: Máxima mañana
    sensor.yw_day2_condition:
      friendly_name: Pasado mañana
    sensor.yw_day2_temperature_min:
      friendly_name: Mínima pasado mañana
    sensor.yw_day2_temperature_max:
      friendly_name: Máxima pasado mañana

    sensor.dark_sky_hourly_summary:
      friendly_name: Resumen horario
    sensor.dark_sky_daily_summary:
      friendly_name: Forecast
    sensor.dark_sky_temperature:
      friendly_name: Temperatura

    camera.weather_svg:
      friendly_name: !secret weather_svg_cam_name

    binary_sensor.workday_sensor:
      friendly_name: Día laborable

    sensor.season:
      icon: mdi:tree
      friendly_name: Estación

    sun.sun:
      friendly_name: Sol

  # Customize entities matching a pattern
  customize_glob:
    "sensor.dark_sky_summ*":
      friendly_name: Resumen
    "sensor.dark_sky_hum*":
      friendly_name: Humedad
    "sensor.dark_sky_press*":
      friendly_name: Presión
    "sensor.dark_sky_apparent_temp*":
      friendly_name: Temperatura aparente
    "sensor.dark_sky_daily_high_apparent_temp*":
      friendly_name: Máxima diaria aparente
      icon: mdi:arrow-collapse-up
    "sensor.dark_sky_daytime_high_temp*":
      friendly_name: Máxima diaria
      icon: mdi:arrow-collapse-up
    "sensor.dark_sky_overnight_low_temp*":
      friendly_name: Mínima nocturna
      icon: mdi:arrow-collapse-down

sun:

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    name: Local Weather
    scan_interval: 1200

binary_sensor:
  # binary_sensor.workday_sensor
  - platform: workday
    country: !secret country_code
    province: !secret province_code
  #  workdays: List of workdays (defaults to mon, tue, wed, thu, fri).
  #  excludes: List of workday excludes (defaults to sat, sun, holiday).

sensor:
  - platform: season

  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 1
      - 2
      - 3
    monitored_conditions:
      - summary
      - hourly_summary
      - daily_summary
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - humidity
      - pressure
    scan_interval: 1200

###############################################################################
# SVG CAMERAS
###############################################################################
camera:
#  - platform: generic
#    name: webcam_playa_1
#    still_image_url: !secret webcam_playa_1
#    scan_interval: 300

#  - platform: generic
#    name: webcam_playa_2
#    still_image_url: !secret webcam_playa_2
#    scan_interval: 300
  # - platform: generic
  #   name: webcam_playa_3
  #   still_image_url: !secret webcam_playa_3

  - platform: generic
    name: weather_svg
    still_image_url: !secret weather_svg_cam_url
    content_type: 'image/svg+xml'
    scan_interval: 1800

#  - platform: generic
#    name: worldtime
#    still_image_url: https://imgs.xkcd.com/comics/now.png
#    scan_interval: 1800
