###############################################################################
# YEELIGHT strip
###############################################################################
homeassistant:
  customize:
    light.yeelight_strip_7811dca21ecf:
      icon: mdi:dots-horizontal
      friendly_name: Tira TV

yeelight:
  scan_interval: 60
  devices:
    192.168.1.46:
      name: yeelight_strip_7811dca21ecf
      transition: 600
      model: strip1
#        use_music_mode: True #(defaults to False)
#        save_on_change: False #(defaults to True)

