AutoFeedback:
  class: EventListener
  module: bot_event_listener
  ha_key: !secret ha_key
  lights_notif: light.cuenco,light.lamparita
  bot_chatids: !secret bot_chatids
  bot_name: !secret bot_name
  bot_nicknames: !secret bot_nicknames
  base_url: !secret base_url

StatsSensors:
  module: time_weighted_moving_average
  class: TimeWeightedMovingAverage
  update_interval: 30
  sensors:
    - sensor_source: sensor.main_power_total
      sensor_publish: sensor.sustained_power_weighted
      name: Power (contador)
      window_minutes: 15
      expected_interval: 5
      precision: 0
    - sensor_source: sensor.nut_ups_power
      sensor_publish: sensor.ups_mean_power
      name: UPS mean Power
      window_minutes: 3
      expected_interval: 30
      precision: 0
    - sensor_source: sensor.humedad_interior
      sensor_publish: sensor.humedad_stats_mean
      name: Humedad interior
      window_minutes: 15
      expected_interval: 15
      precision: 1
    - sensor_source: sensor.temperatura_interior
      sensor_publish: sensor.temperatura_stats_mean
      name: Temperatura interior
      window_minutes: 15
      expected_interval: 15
      precision: 1
    - sensor_source: sensor.temperatura_exterior
      sensor_publish: sensor.temperatura_ext_stats_mean
      name: Temperatura exterior
      window_minutes: 15
      expected_interval: 15
      precision: 1
    - sensor_source: sensor.temperatura_ac
      sensor_publish: sensor.temperatura_ac_mean
      name: Temperatura AC
      window_minutes: 10
      expected_interval: 15
      precision: 1

KitchenLight:
  module: light_with_motion_and_hue_switch
  class: HueSwitchAndMotionControl
  remote_event: deconz_event
  remote_event_filter:
    id: interruptor_cocina
  motion_sensors:
    - binary_sensor.motion_sensor_cocina
    - binary_sensor.mini_motion_cocina
    - binary_sensor.sensor_kitchen_mov1
  light_group: light.cocina
  toggle_automation: input_boolean.app_lights_automation
  scene_schedule:
    kitchen_deep_night:
      from: '01:00:00'
      to: '06:00:00'
      wait_to_turn_off: 30
      turn_on_service_call:
        service: 'scene/turn_on'
        service_data:
          entity_id: 'scene.cocina_cocina_deep_night'
    kitchen_night:
      from: 'sunset - 00:30:00'
      to: 'sunrise + 00:15:00'
      wait_to_turn_off: 60
      turn_on_service_call:
        service: 'scene/turn_on'
        service_data:
          entity_id: 'scene.cocina_cocina_night'
    kitchen_energy:
      from: 'sunrise + 00:14:00'
      to: '13:00:01'
      wait_to_turn_off: 120
      turn_on_service_call:
        service: 'scene/turn_on'
        service_data:
          entity_id: 'scene.cocina_cocina_energy'
    kitchen_concentrate:
      from: '13:00:00'
      to: '17:00:01'
      wait_to_turn_off: 300
      turn_on_service_call:
        service: 'scene/turn_on'
        service_data:
          entity_id: 'scene.cocina_cocina_concentration'
    kitchen_reading:
      from: '17:00:00'
      to: 'sunset - 00:30:01'
      wait_to_turn_off: 150
      turn_on_service_call:
        service: 'scene/turn_on'
        service_data:
          entity_id: 'scene.cocina_cocina_reading'
  default_scene: kitchen_energy
  delay_re_enable_motion_control: 120
  max_delay_motion_off: 900
  rotate_scene_order:
    - kitchen_night
    - kitchen_deep_night
    - kitchen_energy
    - kitchen_concentrate
    - kitchen_reading

#HueTapControl: --> now as automations with 'choose' stages
#  module: hue_tap_controller
#  class: HueTapControl

LastMotionHistory:
  class: MultiBinSensor
  module: multi_bin_sensor_history
  new_entity: sensor.last_motion
  max_history: 20
  binary_sensors:
    binary_sensor.main_door: Puerta principal
    binary_sensor.mirror_eve_bath_door: Puerta baño
    binary_sensor.door_galeria: Puerta Galería
    binary_sensor.door_terraza: Puerta Terraza
    binary_sensor.hall_mov: Hall
    binary_sensor.pasillo_mov: Pasillo
    binary_sensor.sensor_kitchen_mov1: Barra
    binary_sensor.mini_motion_cocina: Cocina
    binary_sensor.motion_sensor_cocina: Cocina (f)
    binary_sensor.sensor_bedroom_mov1: Dormitorio
    binary_sensor.sensor_livingroom_mov1: Salón
    # binary_sensor.sensor_study_mov1: Estudio (mesa)
    binary_sensor.mini_motion_estudio: Estudio
    binary_sensor.motion_sensor_bathroom: Baño
    binary_sensor.cuadro_movimiento: Cuadro
  format_last_changed: '%H:%M:%S'
  icon: mdi:motion-sensor
  friendly_name: Last motion

PeakNotifier:
  class: PeakNotifier
  module: power_alarm
  instant_power: sensor.main_power_total
  sustained_power: sensor.sustained_power
  max_power_peak_kw: 5.2
  max_power_kw: 4.6
  max_power_kw_reset: 3.0
  min_time_high: 30
  min_time_low: 60

KodiMediaSelect:
  class: DynamicKodiInputSelect
  module: kodi_input_select

KodiYoutube:
  module: youtube_search
  class: YoutubeSearch
  input_select: input_select.youtube_videos
  input_text: input_text.q_youtube
  media_player: media_player.kodi
  youtube_key: !secret youtube_key

KodiNotifier:
  class: KodiAssistant
  module: kodi_ambient_lights
  lights_dim_off: light.bola,light.cuenco
  lights_dim_on: light.pie_sofa,light.pie_tv
  lights_off: light.central,light.tira,light.tira_tv

MorningAlarmClock:
  class: AlarmClock
  module: morning_alarm_clock
  alarm_time: input_datetime.alarm_clock_time
  warm_up_time: input_datetime.water_boiler_start_time
  warm_up_boolean: input_boolean.use_heater
  special_alarm_datetime: input_datetime.next_special_wake_up
  alarmdays: mon,tue,wed,thu,fri
  alarmdays_condition: binary_sensor.workday_sensor
  input_boolean_alarm_on: input_boolean.alarm_clock_status
  sunrise_duration: 600
  duration_volume_ramp_sec: 300
  max_volume: 25
  warm_up_time_delta_s: 9000
  # TODO Implement receive postponer action if player stops or pauses!! (manual trigger!)
  postponer_minutos: 7
  room_select: input_select.room_altavoces
  lights_alarm: light.dormitorio,light.tira_cocina
  manual_trigger: input_boolean.manual_trigger_alarmclock
