AutoFeedback:
  class: EventListener
  module: bot_event_listener
  ha_key: !secret ha_key
  lights_notif: light.cuenco,light.lamparita
  bot_chatids: !secret bot_chatids
  bot_name: !secret bot_name
  bot_nicknames: !secret bot_nicknames
  base_url: !secret base_url

HueTapControl:
  module: hue_tap_controller
  class: HueTapControl

PeakNotifier:
  class: PeakNotifier
  module: power_alarm
  instant_power: sensor.main_power_total
  sustained_power: sensor.sustained_power
  max_power_peak_kw: 6.5
  max_power_kw: 4.6
  max_power_kw_reset: 3.0
  min_time_high: 30
  min_time_low: 60

KodiMediaSelect:
  class: DynamicKodiInputSelect
  module: kodi_input_select

KodiYoutube:
  module: youtube_search
  class: YoutubeSearch
  input_select: input_select.youtube_videos
  input_text: input_text.q_youtube
  media_player: media_player.kodi
  youtube_key: !secret youtube_key

KodiNotifier:
  class: KodiAssistant
  module: kodi_ambient_lights
  lights_dim_off: light.bola_grande,light.cuenco
  lights_dim_on: light.pie_sofa,light.pie_tv
  lights_off: light.central,light.tira,light.tira_tv

MorningAlarmClock:
  class: AlarmClock
  module: morning_alarm_clock
  alarm_time: input_datetime.alarm_clock_time
  warm_up_time: input_datetime.water_boiler_start_time
  warm_up_boolean: input_boolean.use_heater
  special_alarm_datetime: input_datetime.next_special_wake_up
  alarmdays: mon,tue,wed,thu,fri
  alarmdays_condition: binary_sensor.workday_sensor
  input_boolean_alarm_on: input_boolean.alarm_clock_status
  sunrise_duration: 600
  duration_volume_ramp_sec: 300
  max_volume: 25
  warm_up_time_delta_s: 9000
  # TODO Implement receive postponer action if player stops or pauses!! (manual trigger!)
  postponer_minutos: 7
  room_select: input_select.room_altavoces
  lights_alarm: light.dormitorio,light.tira_cocina
  manual_trigger: input_boolean.manual_trigger_lacafetera
