homeassistant:
  name: Domus
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  auth_providers:
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret hass_pw
    - type: trusted_networks
      trusted_networks:
      - 192.168.1.0/24
  #      - 127.0.0.1
  packages:  !include_dir_named packages
  customize: !include customize.yaml
  #customize_glob: !include frontend/customize_glob.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

config:

http:
#  base_url: !secret base_url
  cors_allowed_origins:
    - https://cast.home-assistant.io

  ip_ban_enabled: True
  login_attempts_threshold: 50
#  use_x_forwarded_for: true
#  trusted_networks:
#    - 127.0.0.1
#    - 192.168.1.0/24
#    - 172.30.33.2
#    - 172.30.32.2
#  use_x_forwarded_for: True
#  trusted_proxies:
#    - 127.0.0.1
#    - ::1
#    trusted_networks:
#      - 127.0.0.1
#      - ::1
#      - 192.168.0.0/24
#      - fd00::/8
#  use_x_forwarded_for: False
#  trusted_proxies:
logger:
  default: warn
  logs:
    asyncio: error
    aiohttp.server: critical
    homeassistant.bootstrap: info
    # homeassistant.core: error
    frontend: critical
    homeassistant.components.floorplan: debug
    homeassistant.components.device_tracker: error
    homeassistant.components.history: info
    homeassistant.components.http.auth: error
#    homeassistant.components.tplink.switch: critical
    homeassistant.components.yeelight: critical
    homeassistant.components.recorder: info
    homeassistant.components.script: info
    homeassistant.components.sensor.influxdb: error
    homeassistant.components.tts: debug
    homeassistant.components.xiaomi_miio.vacuum: error
    pyShelly: error
    tuyaha.tuyaapi: error
    miio: critical
    DenonAVR: critical
    homeassistant.helpers.entity: error
    custom_components.ambilights.switch: critical
    # custom_components.switch.tuyawifiplug: error

mqtt:
  broker: 192.168.1.10
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: 'hass/status_master'
    payload: 'on'
    qos: !secret mqtt_default_qos
  will_message:
    topic: 'hass/status_master'
    payload: 'off'
    qos: !secret mqtt_default_qos

updater:
  include_used_components: true

cloud:
hassio:
#stream:

discovery:
  ignore:
    - yeelight
    - google_cast
#  enable:
#    - homekit

conversation:
python_script:
wake_on_lan:

# Text to speech
tts:
  platform: google_translate
  language: 'es'

history:
  include:
    domains:
      - sun
      - binary_sensor
      - sensor
      - media_player
      - device_tracker
      - light
      - switch
      - vacuum
      - input_boolean
  exclude:
    entities:
      - sensor.temperatura_ac
      - sensor.temperatura_interior
      - sensor.humedad_interior
      - sensor.date_time
      - sensor.time_utc

logbook:
  include:
    domains:
      - sun
      - automation
      - light
      - switch
      - media_player
      - vacuum
      - script
      - python_script
      - input_boolean
    entities:
      - binary_sensor.mirror_eve_main_door
      - binary_sensor.services_notok

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_db
  username: !secret influxdb_user
  password: !secret influxdb_pass
  default_measurement: state
  exclude:
    entities:
#      - "sensor.floors_(.*)"
      - sensor.hacs
      - sensor.date_time
      - sensor.time_utc
      # No need to store text data:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
#      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
#      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
#      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
#      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      # We have smoothed means:
      - sensor.main_power_total
      - sensor.temperatura_ac
      - sensor.temperatura_interior
      - sensor.humedad_interior
    domains:
      - persistent_notification
      - variable
      - camera
      - configurator
      - input_select
      - input_text
      - group
recorder:
  purge_interval: 1
  purge_keep_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url
  exclude:
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
system_health:
mobile_app:
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
person:
