good_night:
  alias: Buenas noches
  sequence:
  - alias: Apagado de TV
    service: switch.turn_off
    entity_id: switch.03200296dc4f22293a7f,switch.hall_light,switch.ambilight_plus_hue
  - alias: Purificador OFF
    service: fan.turn_off
    entity_id: fan.airpurifier_office
  - alias: CAM Salón ON
    service: python_script.wyzecam_ptz
    data:
      command: cam vigilia
  - alias: Notificación de buenas noches
    service: telegram_bot.send_message
    data_template:
      title: '*¡Buenas noches!*'
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      message: Script de buenas noches *auto-activado*. Apagado de luces, interruptores
        y bajada de persianas.
      disable_notification: true
  - alias: Apagado de luces
    service: light.turn_off
    entity_id: light.salon,light.bano,light.cocina,light.office,light.galeria,light.hall,light.piso
good_morning:
  alias: Buenos días
  sequence:
  - alias: Subida de persianas
    service: cover.open_cover
    entity_id: all
  - alias: Notificación de buenos días
    service: telegram_bot.send_message
    data_template:
      title: '*¡Buenos días!*'
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      message: 'Script de buenos días *auto-activado*: Subida de persianas'
      disable_notification: true
quick_heat_session:
  alias: Quick HEAT session
  sequence:
  - alias: Set heat mode con python script
    service: python_script.set_cool_ac_session
    data:
      mode: heat
quick_cool_session:
  alias: Quick COOL session
  sequence:
  - alias: Set cool mode con python script
    service: python_script.set_cool_ac_session
    data:
      mode: cool
start_vacuum:
  alias: Aspiradora
  sequence:
    service: vacuum.start
    data:
      entity_id: vacuum.robot_aspirador
start_vacuum_office:
  alias: Limpieza office
  sequence:
    service: vacuum.xiaomi_clean_zone
    data:
      entity_id: vacuum.robot_aspirador
      zone:
      - - 25500
        - 29000
        - 28700
        - 31500
      repeats: 2
toggle_position_wyzecampan:
  alias: Swap position WyzeCamPan
  sequence:
    service: python_script.wyzecam_ptz
    data:
      command: cam toggle mode
set_position_escam_door:
  alias: Set position door in ESCAM
  sequence:
    service: shell_command.cmd_set_escam_door
set_position_escam_window:
  alias: Set position window in ESCAM
  sequence:
    service: shell_command.cmd_set_escam_window
play_kodi_pvr:
  alias: Enciende la caja tonta
  sequence:
    service: python_script.start_kodi_play_tv
start_tvshows_mode:
  alias: Set TVShows Mode
  sequence:
    service: python_script.start_tvshows_mode
update_library:
  alias: Update Kodi Library
  sequence:
  - alias: Call Kodi update
    service: kodi.call_method
    data:
      entity_id: media_player.kodi
      method: VideoLibrary.Scan
recent_movies:
  alias: Últimas películas
  sequence:
  - alias: Call Kodi serv
    service: kodi.call_method
    data:
      entity_id: media_player.kodi
      method: VideoLibrary.GetRecentlyAddedMovies
      properties:
      - title
      - year
      - file
      - lastplayed
recent_episodes:
  alias: Últimos episodios
  sequence:
  - alias: Call Kodi serv
    service: kodi.call_method
    data:
      entity_id: media_player.kodi
      method: VideoLibrary.GetRecentlyAddedEpisodes
      properties:
      - showtitle
      - file
      - lastplayed
      - dateadded
      - firstaired
pvr_recordings:
  alias: Últimas grabaciones de TV
  sequence:
  - alias: Call Kodi API
    service: kodi.call_method
    data:
      entity_id: media_player.kodi
      method: PVR.GetRecordings
      properties:
      - title
      - starttime
      - file
pvr_channels:
  alias: Canales de TV
  sequence:
  - alias: Call Kodi serv
    service: kodi.call_method
    data:
      entity_id: media_player.kodi
      method: PVR.GetChannels
      channelgroupid: 1
run_esp_command:
  alias: Run command
  sequence:
  - service: python_script.pub_esp_command
    data_template:
      esp_name: '{{ states.input_select.esp_modules.state  | lower }}'
      command: '{{ states.input_select.esp_command.state | lower}}'
run_dev_command:
  alias: Run dev command
  sequence:
  - service: python_script.dev_command
    data_template:
      command: '{{ states.input_select.dev_command.state  | lower }}'
      command_data: '{{ states.input_text.command_data.state }}'
start_status_sonoff_outlets:
  alias: Requerir estado de Sonoff
  sequence:
  - service: mqtt.publish
    data:
      topic: sonoff/pow/1
      payload: stat
      qos: 1
  - service: mqtt.publish
    data:
      topic: sonoff/simple1
      payload: stat
      qos: 1
inmersion:
  alias: Inmersión
  sequence:
  - entity_id: media_player.nvidia_shield
    service: media_player.turn_on
  - entity_id: switch.ambilight_plus_hue
    service: switch.turn_on
  - data:
      position: 30
    entity_id: cover.shelly_ventanal
    service: cover.set_cover_position
  - data:
      position: 70
    entity_id: cover.shelly_puerta
    service: cover.set_cover_position
  - entity_id: light.tira_tv
    service: light.turn_off
