# travis_secrets.yaml
base_host: secret.com
base_url: https://secret.com
country_code: ES
darksky_api_key: onelongsecretkey
elevation: 0
ext_dir_1: /
ext_dir_2: /usr
gcm_api_key: esjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjas
gcm_sender_id: 342424249766
grafana_db_elec_consumo_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{%
  set ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/vistazo?refresh=1h&orgId=1&panelId=4&from={{
  ((ts_hour - (7*24+1)*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0)
  }}&width=1000&height=800&tz=CET'
grafana_db_elec_power_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{% set
  ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/para-ha-elec24h?refresh=1m&orgId=1&panelId=5&from={{
  ((ts_hour - 24*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0) }}&width=1000&height=800&tz=CET'
grafana_elec_url: https://secret.com/grafana_app/dashboard/db/enerpi?refresh=1m&orgId=1&from=now-7d&to=now
grafana_password: passwordforgrafanaaccess
grafana_url: https://secret.com/grafana_app/dashboard/db/dashb?refresh=1m&orgId=1&from=now-24h&to=now&theme=light
grafana_username: user_gr
hass_email: my@email.com
hass_email_pw: esjwj2idiasfii3rfoq3ifjas
hass_pw: secret
influxdb_db: hass
influxdb_host: 192.168.200.204
influxdb_pass: yeha62hd
influxdb_port: 8086
influxdb_user: hass
kodi_port: 8080
latitude: 0.0
local_ip: 192.168.200.200
longitude: 0.0
maxcio_wifi_plug_1_device_id: localaccessdeviceid
maxcio_wifi_plug_1_host: 192.168.200.73
maxcio_wifi_plug_1_local_key: localaccesskey
motioneye_url: https://secret.com/cams/
mqtt_client_id: client_id
mqtt_default_expiration: 120
mqtt_default_expiration_batt: 900
mqtt_default_qos: 2
mqtt_default_retain: true
mqtt_password: secretkey
mqtt_port: 1883
mqtt_topic_esp32_ener_command: custom_route/id_esp1/command
mqtt_topic_esp32_ener_lwt: custom_route/id_esp1/lwt
mqtt_topic_esp32_ener_status: custom_route/id_esp1/status
mqtt_topic_esp32_ener_stream: custom_route/id_esp1/stream
mqtt_topic_esp_acs_command: custom_route/id_esp5/command
mqtt_topic_esp_acs_lwt: custom_route/id_esp5/lwt
mqtt_topic_esp_acs_status: custom_route/id_esp5/status
mqtt_topic_esp_bathroom_ac_command: custom_route/id_esp8/command
mqtt_topic_esp_bathroom_ac_lwt: custom_route/id_esp8/lwt
mqtt_topic_esp_bathroom_ac_status: custom_route/id_esp8/status
mqtt_topic_esp_bedroom_command: custom_route/id_esp9/command
mqtt_topic_esp_bedroom_lwt: custom_route/id_esp9/lwt
mqtt_topic_esp_bedroom_status: custom_route/id_esp9/status
mqtt_topic_esp_dev1_oled_command: custom_route/id_esp10/command
mqtt_topic_esp_dev1_oled_lwt: custom_route/id_esp10/lwt
mqtt_topic_esp_dev1_oled_status: custom_route/id_esp10/status
mqtt_topic_esp_kitchen_command: custom_route/id_esp6/command
mqtt_topic_esp_kitchen_lwt: custom_route/id_esp6/lwt
mqtt_topic_esp_kitchen_status: custom_route/id_esp6/status
mqtt_topic_esp_livingroom_command: custom_route/id_esp3/command
mqtt_topic_esp_livingroom_lwt: custom_route/id_esp3/lwt
mqtt_topic_esp_livingroom_status: custom_route/id_esp3/status
mqtt_topic_esp_office_command: custom_route/id_esp2/command
mqtt_topic_esp_office_lwt: custom_route/id_esp2/lwt
mqtt_topic_esp_office_status: custom_route/id_esp2/status
mqtt_topic_esp_terraza_command: custom_route/id_esp4/command
mqtt_topic_esp_terraza_lwt: custom_route/id_esp4/lwt
mqtt_topic_esp_terraza_status: custom_route/id_esp4/status
mqtt_topic_esp_wine_command: custom_route/id_esp12/command
mqtt_topic_esp_wine_lwt: custom_route/id_esp12/lwt
mqtt_topic_esp_wine_status: custom_route/id_esp12/status
mqtt_username: usermq
myemail: my@email.com
name: Test
nas_qnap_host: 192.168.200.20
nas_qnap_password: superadminpwd
nas_qnap_username: superadmin
no_ip_password: 123455
no_ip_user: user_noip
openweathermap_api_key: onelongsecretkey
pb_target: email/my@email.com
pihole_host: 192.168.200.248:8080
province_code: CVA
psychrocam_svgchart_url: https://secret.com/svgchart
pushbullet_api_key: esjwj2idiasfii3rfoq3ifjas
radius_home: 1
recorder_db_url: mysql://homeassistant:123455@localhost/hassdb
recorder_purge_days: 14
ssh_cmd_rpi_temp_rpi3dev1: ssh pi@rpi3dev1 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpi3dev2: ssh pi@rpi3dev2 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpi3dev3: ssh pi@rpi3dev3 cat /sys/class/thermal/thermal_zone0/temp
telegram_bot_all_targets: 1234556,9876354
telegram_bot_api_key: esjwj2idiasfii3rfoq3ifjas
telegram_bot_chat_id_2: 9876354
telegram_bot_chat_id_2_name: N2
telegram_bot_chat_id_admin: 1234556
telegram_bot_chat_id_admin_name: N1
telegram_bot_group: -9876354
time_zone: Europe/Madrid
url_saas_torrent_search: https://secret.com/search
weather_location: secret
weather_svg_cam_name: City
weather_svg_cam_url: https://www.yr.no/place/country/state/city/meteogram.svg
weblink_contab_url: https://secret.com/contabilidad/
weblink_hassio_lan: http://192.168.200.200:8123/
weblink_nas_qnap_url: https://qlink.to/MYID
weblink_nas_url: https://secret.com/index.cgi
xiaomi_vacuum_robot_ip: 192.168.200.229
xiaomi_vacuum_robot_token: '12345678901234567890123456789012'
z2_icon: mdi:icon
z2_latitude: 0.0
z2_longitude: 0.0
z2_name: z2
z2_radius: 1
