# travis_secrets.yaml
base_host: secret.com
base_url: https://secret.com
country_code: ES
darksky_api_key: onelongsecretkey
elevation: 0
ext_dir_1: /
ext_dir_2: /usr
gcm_api_key: esjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjas
gcm_sender_id: 342424249766
grafana_db_elec_consumo_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{%
  set ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/vistazo?refresh=1h&orgId=1&panelId=4&from={{
  ((ts_hour - (7*24+1)*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0)
  }}&width=1000&height=800&tz=CET'
grafana_db_elec_power_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{% set
  ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/para-ha-elec24h?refresh=1m&orgId=1&panelId=5&from={{
  ((ts_hour - 24*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0) }}&width=1000&height=800&tz=CET'
grafana_elec_url: https://secret.com/grafana_app/dashboard/db/enerpi?refresh=1m&orgId=1&from=now-7d&to=now
grafana_password: passwordforgrafanaaccess
grafana_url: https://secret.com/grafana_app/dashboard/db/dashb?refresh=1m&orgId=1&from=now-24h&to=now&theme=light
grafana_username: user_gr
hass_email: my@email.com
hass_email_pw: esjwj2idiasfii3rfoq3ifjas
hass_pw: secret
influxdb_db: hass
influxdb_host: 192.168.200.204
influxdb_pass: yeha62hd
influxdb_port: 8086
influxdb_user: hass
kodi_port: 8080
latitude: 0.0
local_ip: 192.168.200.200
longitude: 0.0
maxcio_wifi_plug_1_device_id: localaccessdeviceid
maxcio_wifi_plug_1_host: 192.168.200.73
maxcio_wifi_plug_1_local_key: localaccesskey
motioneye_url: https://secret.com/cams/
mqtt_client_id: client_id
mqtt_default_expiration: 120
mqtt_default_expiration_batt: 900
mqtt_default_qos: 2
mqtt_default_retain: true
mqtt_password: secretkey
mqtt_port: 1883
mqtt_topic_esp32_ener_command: custom_route/id_esp1/command
mqtt_topic_esp32_ener_lwt: custom_route/id_esp1/lwt
mqtt_topic_esp32_ener_status: custom_route/id_esp1/status
mqtt_topic_esp32_ener_stream: custom_route/id_esp1/stream
mqtt_topic_esp_acs_command: custom_route/id_esp5/command
mqtt_topic_esp_acs_lwt: custom_route/id_esp5/lwt
mqtt_topic_esp_acs_status: custom_route/id_esp5/status
mqtt_topic_esp_bathroom_ac_command: custom_route/id_esp8/command
mqtt_topic_esp_bathroom_ac_lwt: custom_route/id_esp8/lwt
mqtt_topic_esp_bathroom_ac_status: custom_route/id_esp8/status
mqtt_topic_esp_bedroom_command: custom_route/id_esp9/command
mqtt_topic_esp_bedroom_lwt: custom_route/id_esp9/lwt
mqtt_topic_esp_bedroom_status: custom_route/id_esp9/status
mqtt_topic_esp_dev1_oled_command: custom_route/id_esp10/command
mqtt_topic_esp_dev1_oled_lwt: custom_route/id_esp10/lwt
mqtt_topic_esp_dev1_oled_status: custom_route/id_esp10/status
mqtt_topic_esp_kitchen_command: custom_route/id_esp6/command
mqtt_topic_esp_kitchen_lwt: custom_route/id_esp6/lwt
mqtt_topic_esp_kitchen_status: custom_route/id_esp6/status
mqtt_topic_esp_livingroom_command: custom_route/id_esp3/command
mqtt_topic_esp_livingroom_lwt: custom_route/id_esp3/lwt
mqtt_topic_esp_livingroom_status: custom_route/id_esp3/status
mqtt_topic_esp_office_command: custom_route/id_esp2/command
mqtt_topic_esp_office_lwt: custom_route/id_esp2/lwt
mqtt_topic_esp_office_status: custom_route/id_esp2/status
mqtt_topic_esp_terraza_command: custom_route/id_esp4/command
mqtt_topic_esp_terraza_lwt: custom_route/id_esp4/lwt
mqtt_topic_esp_terraza_status: custom_route/id_esp4/status
mqtt_topic_esp_wine_command: custom_route/id_esp12/command
mqtt_topic_esp_wine_lwt: custom_route/id_esp12/lwt
mqtt_topic_esp_wine_status: custom_route/id_esp12/status
mqtt_username: usermq
myemail: my@email.com
name: Test
nas_qnap_host: 192.168.200.20
nas_qnap_password: superadminpwd
nas_qnap_username: superadmin
no_ip_password: 123455
no_ip_user: user_noip
openweathermap_api_key: onelongsecretkey
pb_target: email/my@email.com
pihole_host: 192.168.200.248:8080
province_code: CVA
psychrocam_svgchart_url: https://secret.com/svgchart
pushbullet_api_key: esjwj2idiasfii3rfoq3ifjas
radius_home: 1
recorder_db_url: mysql://homeassistant:123455@localhost/hassdb
recorder_purge_days: 14
ssh_cmd_rpi_temp_rpi3dev1: ssh pi@rpi3dev1 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpi3dev2: ssh pi@rpi3dev2 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpi3dev3: ssh pi@rpi3dev3 cat /sys/class/thermal/thermal_zone0/temp
telegram_bot_all_targets: 1234556,9876354
telegram_bot_api_key: esjwj2idiasfii3rfoq3ifjas
telegram_bot_chat_id_2: 9876354
telegram_bot_chat_id_2_name: N2
telegram_bot_chat_id_admin: 1234556
telegram_bot_chat_id_admin_name: N1
telegram_bot_group: -9876354
time_zone: Europe/Madrid
url_saas_torrent_search: https://secret.com/search
weather_location: secret
weather_svg_cam_name: City
weather_svg_cam_url: https://www.yr.no/place/country/state/city/meteogram.svg
weblink_contab_url: https://secret.com/contabilidad/
weblink_hassio_lan: http://192.168.200.200:8123/
weblink_nas_qnap_url: https://qlink.to/MYID
weblink_nas_url: https://secret.com/index.cgi
xiaomi_vacuum_robot_ip: 192.168.200.229
xiaomi_vacuum_robot_token: '12345678901234567890123456789012'
z2_icon: mdi:icon
z2_latitude: 0.0
z2_longitude: 0.0
z2_name: z2
z2_radius: 1

person_id_carmen: carmen1998586594
person_id_eu: eugenio1234567891
ibeacon_home_id: 00000000-9FAA-CCCC-DDDD-EEEE99123123
ibeacon_home_major: 10541
ibeacon_home_minor_entrada: 61841
ibeacon_home_minor_estudio: 61842
ibeacon_home_minor_salon: 61843
aemet_local_station_id: 8037

ssh_cmd_rpi_temp_rpi4: ssh pi@192.168.200.111 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpizerocam: ssh someone@192.168.200.83 cat /sys/class/thermal/thermal_zone0/temp
ssh_cmd_rpi_temp_rpizerocam2: ssh someone@192.168.200.84 cat /sys/class/thermal/thermal_zone0/temp
tuya_app_pwd: secretkey
tuya_app_user: someone@gmail.com
tplink_host_ip: 192.168.200.151
tplink_host_ip2: 192.168.200.152
hue_bridge_host: 192.168.200.5
hue_bridge_token: I5NWViZTUwZGUxZjY0ZGY4YWQxMTg5ZmU1ZmI1MD
weblink_hue_bridge: http://192.168.200.5/api/I5NWViZTUwZGUxZjY0ZGY4YWQxMTg5ZmU1ZmI1MD
wyzecam1_password: secretkey
wyzecam1_username: someone
wyzecam2_password: secretkey
wyzecam2_username: someone
wyzecampan1_username: someone
wyzecampan1_password: secretkey
wyzecam1_still_image_url: https://192.168.200.70/cgi-bin/currentpic.cgi
wyzecam1_stream_source: rtsp://192.168.200.70:8554/unicast
wyzecam2_still_image_url: https://192.168.200.72/cgi-bin/currentpic.cgi
wyzecam2_stream_source: rtsp://192.168.200.72:8554/unicast
wyzecampan1_still_image_url: https://192.168.200.71/cgi-bin/currentpic.cgi
wyzecampan1_stream_source: rtsp://192.168.200.71:8554/unicast
xiaomi_air_purifier_ip: 192.168.200.116
xiaomi_air_purifier_token: aaabbbcccdddeeefff00011122233345
denon_heos_username: my@email.com
denon_heos_password: secretkey
denon_host: 192.168.200.85
ha_cloud_email: my@email.com
ios_notifier_main: mobile_app_iphone
ios_notifier_main_ipad: mobile_app_ipad_someone
ios_notifier_secondary: mobile_app_iphone_other
ios_notifier_secondary_ipad: mobile_app_ipad_another
docker_hub_user: someone
docker_hub_pwd: secretkey
kodi_app_pw: secretkey
kodi_app_user: someone
shelly_pwd: secretkey
shelly_user: someone
ifttt_key: secretkey
ifttt_user: someone
github_personal_token_hacs: secretkey
ha_cloud_pwd: secretkey
aemet_opendata_api_key: secretkey
motioneye_rpizero2_snapshot_url: http://192.168.200.84/picture/1/current/?_username=someone&_signature=secretkey
motioneye_rpizero_snapshot_url: http://192.168.200.83/picture/1/current/?_username=someone&_signature=secretkey
motioneye_rpizero_stream_url: http://192.168.200.83:8081
escam_motioneye_local_snapshot: http://192.168.200.67:8765/picture/3/current/?_username=someone&_signature=secretkey
escam_rstp_url: rtsp://192.168.200.7:554/user=someone&password=secretkey&channel=1&stream=0.sdp?
motioneye_rpizero_admin_pwd: secretkey
motioneye_rpizero_user_pwd: secretkey
mqtt_default_expiration_long: 360
pihole_pwd: secretkey
iotlink_topic_w10_cpu_usage: iotlink/home/windowspc/windows-monitor/stats/cpu
iotlink_topic_w10_online: iotlink/home/windowspc/lwt
iotlink_topic_w10_ram_usage: iotlink/home/windowspc/windows-monitor/stats/memory/usage
iotlink_topic_w10_shutdown: iotlink/home/windowspc/commands/shutdown
iotlink_topic_w10_suspend: iotlink/home/windowspc/commands/suspend
iotlink_topic_w10_wol_mac: 0C:9D:59:2D:A3:21
local_ip_iphone6s: 192.168.200.122
local_ip_iphonex: 192.168.200.118
maxcio_wifi_plug_1_mac: dc:4f:22:31:32:33
owntracks_encryption_key: 5fd04d8d7d27b6dfee00f8c10ea07191
owntracks_webhook: https://secret.com/api/webhook/5d4fd0b3b42778cf50abf7fbf49d296a0fc7cc0907e6587a8a6d84a15526501c
philips_tv_api_password: e2637fd18aaac996432509e265dcfbeddb9f7536b24b898e4c83ed6d83d79ee5
philips_tv_api_username: j6RTUzg8VRDVOLE5
philips_tv_host: 192.168.200.82
sentry_dsn: https://a2467427bf81450684b42f6efa406888@sentry.io/8849371
user_id_carmen: e8393473fe6201dd0a8d2e4ed156284f
user_id_eu: bbc66c94ae4966b245319b64f0e6045a
sonos_host_1: 192.168.200.142
sonos_host_2: 192.168.200.150
shield_tv_host: 192.168.200.79
shelly_id_cover_puerta: BA32C4
shelly_id_cover_ventanal: 6991CC
shelly_id_cuadro_alerts: 8CAA380B5059
shelly_id_cuadro_mov: E09806EC2C8C
shelly_id_em: F7A050
shelly_id_hall: 8CAA549B5058
z3_name: School
z3_radius: 500
z3_icon: mdi:school
z4_icon: mdi:home-roof
z4_name: Hometown
z4_radius: 300
z5_icon: mdi:home-roof
z5_name: Hometown 2
z5_radius: 500
z3_latitude: 22.42
z4_latitude: 22.34
z5_latitude: 22.35
z3_longitude: -2.63
z4_longitude: -1.90
z5_longitude: -1.8
token_motioneye: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOi0hAzcIImyJjyiwJ0EMQz2hfFdMxI3ASUTYYDFzDDXzMlMZmMTMOC5iTJNWQUDMOZ6MxMjcNoTOmDzwm44MhMwsMMTINm.JIcAthPUruPRNdW3qakSBlFCUfSNFyLIhR8mB3E_wXG
token_speedtest: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiiozDTJDmhfsyEM5mDwYDMFMwMhTQdUQy4UMWMiMxT2FwcmNTMzljA0MOXOZzIcjAMSYMNz3N4mIM6C0xJTDZJIhzOIMm.DQxwmUF-49hSl8HS5bxFrtUYcYeGNNgfFqRBAe4JacB
token_test_access: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOihTFMToNjxZmDJDzMQ0hwcOMmsDDiUiONNwm0QWCJzMTUy4AOSMMzyYw4jMmmIThDdxIIcMzf5MTAlzF3ZXIEMMJMM6Y2.6E9iOye0SnmhyTAwWqD-PNLLQPRYFO89_AwXr1_IZLo
